// <auto-generated />
using System;
using FinalNewBankApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalNewBankApp.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20260304152038_Fixatable")]
    partial class Fixatable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalNewBankApp.BankTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccountBaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Transaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountBaseId");

                    b.ToTable("BankTransactions");
                });

            modelBuilder.Entity("FinalNewBankApp.Base.AccountBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AccountBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FinalNewBankApp.Accounts.BankAccount", b =>
                {
                    b.HasBaseType("FinalNewBankApp.Base.AccountBase");

                    b.HasDiscriminator().HasValue("BankAccount");
                });

            modelBuilder.Entity("FinalNewBankApp.Accounts.IskAccount", b =>
                {
                    b.HasBaseType("FinalNewBankApp.Base.AccountBase");

                    b.HasDiscriminator().HasValue("IskAccount");
                });

            modelBuilder.Entity("FinalNewBankApp.Accounts.UddevallaAccount", b =>
                {
                    b.HasBaseType("FinalNewBankApp.Base.AccountBase");

                    b.HasDiscriminator().HasValue("UddevallaAccount");
                });

            modelBuilder.Entity("FinalNewBankApp.BankTransaction", b =>
                {
                    b.HasOne("FinalNewBankApp.Base.AccountBase", "Account")
                        .WithMany("BankTransactions")
                        .HasForeignKey("AccountBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FinalNewBankApp.Base.AccountBase", b =>
                {
                    b.Navigation("BankTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
